language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
  - build
script:
  - npm test
  - CI=false ; npm run build
deploy:
  provider: s3
  access_key_id: $aws_access_key_id
  secret_access_key: $secret_access_key
  bucket: "demo.atila.ca"
  skip_cleanup: true
  local_dir: build