language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
  - build
script:
  - npm test
  - CI=false ; npm run build
  - npm run deploy -- --repo "https://$github_token@github.com/client-web-app"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build