name: Continuous Integration

on:
  - push

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm rebuild

      - name: Test
        run: npm run test